health_app/urls.py
"""Defines URL patterns for health_app."""

from django.urls import path

from . import views

app_name = 'health_app'
urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    # Page that shows all symptoms
    path('symptoms/', views.symptoms, name='symptoms'),
]

health_app_python/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('health_app.urls')),
]

health_app/models.py
from django.db import models


# Create your models here.

class Symptom(models.Model):
    """A symptom the user is experiencing."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Notes about symptom"""
    symptom = models.ForeignKey(Symptom, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now=True)


class Meta:
    verbose_name_plural = 'entries'


def __str__(self):
    """Return a string representation of the model"""
    return f"{self.text[:50]}..."

health_app/views.py
from django.shortcuts import render
from .models import Symptom


# Create your views here.
def index(request):
    """The home page for Health App."""
    return render(request, 'health_app/index.html')


def symptoms(request):
    """Show all symptoms"""
    symptoms = Symptom.objects.order_by('date_added')
    context = {'symptoms': symptoms}
    return render(request, 'health_app/symptoms.html', context)

health_app/templates/health_app/base.html
<!--This file will contain elements common to all pages.-->

<p>
    <a href="{% url 'health_app:index' %}">Home</a>
     |
    <a href="{% url 'health_app:symptoms' %}">Symptoms</a>
</p>

{% block content %}{% endblock content %}

health_app/templates/health_app/index.html
{% extends "health_app/base.html" %}

{% block content %}

<p>Health app</p>
<p>Track your symptoms here.</p>

{% endblock content %}

health_app/templates/health_app/symptoms.html
{% extends "health_app/base.html" %}

{% block content %}

    <p>Symptoms</p>

    <ul>
    {% for symptom in symptoms %}
        <li>
            {{ symptom }}
        </li>
    {% empty %}
    <li>
        No symptoms have been added yet.
    </li>
    {% endfor %}
    </ul>

{% endblock content %}